<?php

/**
 * @file
 * Contains customers.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function customers_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the customers module.
    case 'help.page.customers':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom Entity For Customers') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_theme().
 */
function customers_theme() {
  $theme = [];
  $theme['customer_entity'] = [
    'render element' => 'elements',
    'file' => 'customer_entity.page.inc',
    'template' => 'customer_entity',
  ];
  $theme['customer_entity_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'customer_entity.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function customers_theme_suggestions_customer_entity(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#customer_entity'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'customer_entity__' . $sanitized_view_mode;
  $suggestions[] = 'customer_entity__' . $entity->bundle();
  $suggestions[] = 'customer_entity__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'customer_entity__' . $entity->id();
  $suggestions[] = 'customer_entity__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
